### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by kawrou**
Basic styling on homepage. 
There's not service for scraping website but there is a file in service used for mocking it.
Mocked useNavigate in tests. If the name of routes will change in the future, need to update in test and page. 

Will make a new ticket to combine @ben-dh3 navbar and creating a component for web scraping input form.

### CODE REVIEW

**Comment by kawrou** [comment]
Screenshot 2024-02-28 at 13 01 16

**Comment by ben-dh3** [comment]
Looks good! Do we need the tests for the feedpage?

**Review by Ro-0171 — APPROVED** [review]

**Comment by kawrou** [comment]
> Looks good! Do we need the tests for the feedpage?

I've renamed them to be RecipeCollection page.

**Review by ben-dh3 — APPROVED** [review]

**Comment by ben-dh3** [comment]
Actually, you won't need to render the navbar component in the homepage - I rendered it in App.jsx so it is on all pages!

**Comment by kawrou** [comment]
> Actually, you won't need to render the navbar component in the homepage - I rendered it in App.jsx so it is on all pages!

Just realized. Been fixed

**Review by gabrielaehrenbrink — COMMENTED** [review]
Might need to resolve some conflicts from the latest merge, I'd say to pull again from main just to double check there are no conflicts. Then all good.

**Comment by kawrou** [comment]
> Might need to resolve some conflicts from the latest merge, I'd say to pull again from main just to double check there are no conflicts. Then all good.

Pulled from main and integrated @gabrielaehrenbrink code. 
Added some comments for context. 
Will need to refactor the code down the line.

**Pull request merged**
